name: Java CI with Gradle

on: [push, pull_request]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name : Checkout Service Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

